const char* coord_MakeMetaTableString = (
"--[[This chunk will return the metatable used for coords in the basic Win32 implementation of the LuaWinCon library. It is compatible with\n"
"both Lua 5.1 and Lua 5.2]]\n"
"local meta = {}\n"
"local method = {}\n"
"\n"
"--We want the functions here to run as fast as possible, localize EVERYTHING\n"
"local tonumber, setmetatable, floor, fmt = tonumber, setmetatable, math.floor, string.format\n"
"\n"
"local function IsACoord(cord)\n"
"    return tonumber(cord[1]) and tonumber(cord[2])\n"
"end\n"
"\n"
"local function MakeCoord(cord)\n"
"    return setmetatable(cord, meta)\n"
"end\n"
"\n"
"function meta.__add(op1, op2)\n"
"    if not IsACoord(op1) and IsACoord(op2) then\n"
"        error(\"Tried to add a non-coord to a coord!\", 2)\n"
"    else\n"
"        return MakeCoord{floor(op1[1]+op2[1]), floor(op1[2]+op2[2])}\n"
"    end\n"
"end\n"
"\n"
"function meta.__mul(op1, op2) --I feel that this could be better-written.\n"
"    local cord, num = nil, nil\n"
"    if IsACoord(op1) then\n"
"        if IsACoord(op2) then\n"
"            error(\"Tried to multiply a coord by a coord!\", 2)\n"
"        elseif not tonumber(op2) then\n"
"            error(\"Tried to multiply a coord by a non-number!\")\n"
"        else\n"
"            cord, num = op1, op2\n"
"        end\n"
"    else --IsACoord(op2) *must* be true in this case\n"
"        if not tonumber(op1) then\n"
"            error(\"Tried to multiply a coord by a non-number!\")\n"
"        else\n"
"            cord, num = op2, op1\n"
"        end\n"
"    end\n"
"    \n"
"    return MakeCoord{floor(cord[1]*num), floor(cord[2]*num)}\n"
"end\n"
"\n"
"do local map_table = {\n"
"    [\"x\"] = 1,\n"
"    [\"w\"] = 1,\n"
"    [\"y\"] = 2,\n"
"    [\"h\"] = 2\n"
"}\n"
"\n"
"function meta.__index(cord, key)\n"
"    local mapped = map_table[key]\n"
"    return mapped and cord[mapped] or method[key]\n"
"end\n"
"\n"
"function meta.__newindex(cord, key, val)\n"
"    local mapped = map_table[key]\n"
"    if mapped then cord[mapped] = val else cord[key] = val end\n"
"end \n"
"\n"
"end\n"
"\n"
"function meta.__tostring(cord)\n"
"    return fmt(\"(%d, %d)\", cord[1], cord[2])\n"
"end\n"
"\n"
"return meta\n");